const { Node, Edge } = require('./models');
const populateDatabase = async () => {
  // Insert nodes
  const nodes = [
    { label: 'Handaxe', year: -1760000 },
    { label: 'Control of Fire', year: -1000000 },
    { label: 'Flint Knapping', year: -1760000 },
    { label: 'Spears', year: -400000 },
    { label: 'Bow and Arrow', year: -64000 },
    { label: 'Fishing Techniques', year: -40000 },
    { label: 'Basic Clothing', year: -100000 },
    { label: 'Pottery', year: -29000 },
    { label: 'Animal Domestication', year: -10000 },
    { label: 'Agriculture', year: -12000 },
    { label: 'Grinding Stone', year: -60000 },
    { label: 'Weaving', year: -12000 },
    { label: 'Basketry', year: -8000 },
    { label: 'Fishhook', year: -16000 },
    { label: 'Basic Shelters', year: -400000 },
    { label: 'Rock Art', year: -400000 },
    { label: 'Burial Practices', year: -100000 },
    { label: 'Bronze Smelting', year: -3500 },
    { label: 'Chariots', year: -3000 },
    { label: 'Early Writing Systems', year: -3500 },
    { label: 'Irrigation', year: -6000 },
    { label: 'Plow', year: -4000 },
    { label: 'Metal Alloys', year: null },
    { label: 'Urbanization', year: null },
    { label: 'Copper Smelting', year: -5000 },
    { label: 'Tin Mining', year: -3500 },
    { label: 'Wheel', year: -3500 },
    { label: 'Metallurgy', year: -6000 },
    { label: 'Canoe', year: -8000 },
    { label: 'Iron Smelting', year: -1200 },
    { label: 'Blacksmithing', year: -1000 },
    { label: 'Gunpowder', year: 850 },
    { label: 'Alchemy', year: 300 },
    { label: 'Siege Engines', year: 400 },
    { label: 'Cannon', year: 1320 },
    { label: 'Scavenging', year: -2000000 },
    { label: 'Primitive Hunting', year: -1500000 },
    { label: 'Primitive Fishing', year: -1000000 },
    { label: 'Trapping', year: -300000 },
    { label: 'Spear Fishing', year: -250000 },
    { label: 'Crop Cultivation', year: -10000 },
    { label: 'Animal Husbandry', year: -9000 },
    { label: 'Net Fishing', year: -8300 },
    { label: 'Angling', year: -2000 },
    { label: 'Plow Agriculture', year: -3000 },
    { label: 'Iron Plow', year: -500 },
    { label: 'Crop Rotation', year: 600 },
    { label: 'Windmill', year: 1100 },
    { label: 'Mechanized Farming', year: 1700 },
    { label: 'Fertilizer', year: 1840 },
    { label: 'Counting', year: -50000 },
    { label: 'Tally Marks', year: -30000 },
    { label: 'Numeral System', year: -5000 },
    { label: 'Addition and Subtraction', year: -20000 },
    { label: 'Multiplication and Division', year: -10000 },
    { label: 'Measurement', year: -15000 },
    { label: 'Square and Circle Geometry', year: -4000 },
    { label: 'Fractions', year: -2500 },
    { label: 'Square Roots', year: -1500 },
    { label: 'Equations', year: -1800 },
    { label: 'Sine and Cosine', year: -1500 },
  ];
  const createdNodes = await Node.bulkCreate(nodes);

  // Create a mapping from label to ID for easier edge creation
  const nodeMapping = {};
  createdNodes.forEach((node, i) => {
    nodeMapping[nodes[i].label] = node.id;
  });

  // Insert edges
  const edges = [
    { target_node_id: nodeMapping['Flint Knapping'], source_node_id: nodeMapping['Handaxe'] },
    { target_node_id: nodeMapping['Spears'], source_node_id: nodeMapping['Flint Knapping'] },
    { target_node_id: nodeMapping['Spears'], source_node_id: nodeMapping['Control of Fire'] },
    { target_node_id: nodeMapping['Bow and Arrow'], source_node_id: nodeMapping['Flint Knapping'] },
    { target_node_id: nodeMapping['Fishing Techniques'], source_node_id: nodeMapping['Spears'] },
    { target_node_id: nodeMapping['Basic Clothing'], source_node_id: nodeMapping['Weaving'] },
    { target_node_id: nodeMapping['Pottery'], source_node_id: nodeMapping['Control of Fire'] },
    { target_node_id: nodeMapping['Pottery'], source_node_id: nodeMapping['Wheel'] },
    { target_node_id: nodeMapping['Agriculture'], source_node_id: nodeMapping['Animal Domestication'] },
    { target_node_id: nodeMapping['Grinding Stone'], source_node_id: nodeMapping['Agriculture'] },
    { target_node_id: nodeMapping['Grinding Stone'], source_node_id: nodeMapping['Flint Knapping'] },
    { target_node_id: nodeMapping['Weaving'], source_node_id: nodeMapping['Agriculture'] },
    { target_node_id: nodeMapping['Basketry'], source_node_id: nodeMapping['Weaving'] },
    { target_node_id: nodeMapping['Fishhook'], source_node_id: nodeMapping['Fishing Techniques'] },
    { target_node_id: nodeMapping['Fishhook'], source_node_id: nodeMapping['Flint Knapping'] },
    { target_node_id: nodeMapping['Basic Shelters'], source_node_id: nodeMapping['Handaxe'] },
    { target_node_id: nodeMapping['Basic Shelters'], source_node_id: nodeMapping['Control of Fire'] },
    { target_node_id: nodeMapping['Rock Art'], source_node_id: nodeMapping['Handaxe'] },
    { target_node_id: nodeMapping['Burial Practices'], source_node_id: nodeMapping['Basic Shelters'] },
    { target_node_id: nodeMapping['Bronze Smelting'], source_node_id: nodeMapping['Copper Smelting'] },
    { target_node_id: nodeMapping['Bronze Smelting'], source_node_id: nodeMapping['Tin Mining'] },
    { target_node_id: nodeMapping['Bronze Smelting'], source_node_id: nodeMapping['Metal Alloys'] },
    { target_node_id: nodeMapping['Chariots'], source_node_id: nodeMapping['Wheel'] },
    { target_node_id: nodeMapping['Chariots'], source_node_id: nodeMapping['Animal Domestication'] },
    { target_node_id: nodeMapping['Irrigation'], source_node_id: nodeMapping['Agriculture'] },
    { target_node_id: nodeMapping['Plow'], source_node_id: nodeMapping['Agriculture'] },
    { target_node_id: nodeMapping['Metal Alloys'], source_node_id: nodeMapping['Metallurgy'] },
    { target_node_id: nodeMapping['Urbanization'], source_node_id: nodeMapping['Basic Shelters'] },
    { target_node_id: nodeMapping['Urbanization'], source_node_id: nodeMapping['Agriculture'] },
    { target_node_id: nodeMapping['Copper Smelting'], source_node_id: nodeMapping['Metallurgy'] },
    { target_node_id: nodeMapping['Copper Smelting'], source_node_id: nodeMapping['Control of Fire'] },
    { target_node_id: nodeMapping['Metallurgy'], source_node_id: nodeMapping['Control of Fire'] },
    { target_node_id: nodeMapping['Canoe'], source_node_id: nodeMapping['Handaxe'] },
    { target_node_id: nodeMapping['Canoe'], source_node_id: nodeMapping['Basic Shelters'] },
    { target_node_id: nodeMapping['Iron Smelting'], source_node_id: nodeMapping['Copper Smelting'] },
    { target_node_id: nodeMapping['Blacksmithing'], source_node_id: nodeMapping['Iron Smelting'] },
    { target_node_id: nodeMapping['Gunpowder'], source_node_id: nodeMapping['Alchemy'] },
    { target_node_id: nodeMapping['Alchemy'], source_node_id: nodeMapping['Metallurgy'] },
    { target_node_id: nodeMapping['Siege Engines'], source_node_id: nodeMapping['Blacksmithing'] },
    { target_node_id: nodeMapping['Cannon'], source_node_id: nodeMapping['Gunpowder'] },
    { target_node_id: nodeMapping['Cannon'], source_node_id: nodeMapping['Blacksmithing'] },
    { target_node_id: nodeMapping['Cannon'], source_node_id: nodeMapping['Siege Engines'] },
    { target_node_id: nodeMapping['Primitive Hunting'], source_node_id: nodeMapping['Scavenging'] },
    { target_node_id: nodeMapping['Primitive Hunting'], source_node_id: nodeMapping['Handaxe'] },
    { target_node_id: nodeMapping['Primitive Fishing'], source_node_id: nodeMapping['Scavenging'] },
    { target_node_id: nodeMapping['Trapping'], source_node_id: nodeMapping['Primitive Hunting'] },
    { target_node_id: nodeMapping['Trapping'], source_node_id: nodeMapping['Handaxe'] },
    { target_node_id: nodeMapping['Spear Fishing'], source_node_id: nodeMapping['Spears'] },
    { target_node_id: nodeMapping['Spear Fishing'], source_node_id: nodeMapping['Primitive Fishing'] },
    { target_node_id: nodeMapping['Crop Cultivation'], source_node_id: nodeMapping['Animal Domestication'] },
    { target_node_id: nodeMapping['Crop Cultivation'], source_node_id: nodeMapping['Grinding Stone'] },
    { target_node_id: nodeMapping['Animal Husbandry'], source_node_id: nodeMapping['Animal Domestication'] },
    { target_node_id: nodeMapping['Net Fishing'], source_node_id: nodeMapping['Weaving'] },
    { target_node_id: nodeMapping['Net Fishing'], source_node_id: nodeMapping['Spear Fishing'] },
    { target_node_id: nodeMapping['Angling'], source_node_id: nodeMapping['Weaving'] },
    { target_node_id: nodeMapping['Angling'], source_node_id: nodeMapping['Primitive Fishing'] },
    { target_node_id: nodeMapping['Plow Agriculture'], source_node_id: nodeMapping['Crop Cultivation'] },
    { target_node_id: nodeMapping['Plow Agriculture'], source_node_id: nodeMapping['Plow'] },
    { target_node_id: nodeMapping['Iron Plow'], source_node_id: nodeMapping['Plow Agriculture'] },
    { target_node_id: nodeMapping['Iron Plow'], source_node_id: nodeMapping['Iron Smelting'] },
    { target_node_id: nodeMapping['Crop Rotation'], source_node_id: nodeMapping['Plow Agriculture'] },
    { target_node_id: nodeMapping['Windmill'], source_node_id: nodeMapping['Plow Agriculture'] },
    { target_node_id: nodeMapping['Mechanized Farming'], source_node_id: nodeMapping['Plow Agriculture'] },
    { target_node_id: nodeMapping['Fertilizer'], source_node_id: nodeMapping['Crop Rotation'] },
    { target_node_id: nodeMapping['Fertilizer'], source_node_id: nodeMapping['Mechanized Farming'] },
    { target_node_id: nodeMapping['Tally Marks'], source_node_id: nodeMapping['Counting'] },
    { target_node_id: nodeMapping['Numeral System'], source_node_id: nodeMapping['Counting'] },
    { target_node_id: nodeMapping['Addition and Subtraction'], source_node_id: nodeMapping['Counting'] },
    { target_node_id: nodeMapping['Multiplication and Division'], source_node_id: nodeMapping['Addition and Subtraction'] },
    { target_node_id: nodeMapping['Measurement'], source_node_id: nodeMapping['Counting'] },
    { target_node_id: nodeMapping['Square and Circle Geometry'], source_node_id: nodeMapping['Measurement'] },
    { target_node_id: nodeMapping['Fractions'], source_node_id: nodeMapping['Multiplication and Division'] },
    { target_node_id: nodeMapping['Square Roots'], source_node_id: nodeMapping['Square and Circle Geometry'] },
    { target_node_id: nodeMapping['Equations'], source_node_id: nodeMapping['Square and Circle Geometry'] },
    { target_node_id: nodeMapping['Sine and Cosine'], source_node_id: nodeMapping['Square and Circle Geometry'] },
  ];
  await Edge.bulkCreate(edges);
};

populateDatabase().then(() => {
  console.log('Database populated.');
}).catch((error) => {
  console.error('Error populating database:', error);
});
